In [ ]:
# Question1a
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])


Reversed: [5 4 6 3 2 1]


In [ ]:
# Question1b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.ravel())
print(array1.flatten())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
#Question1c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1, arr2)


True

In [ ]:
# Question1d
x = np.array([1,2,3,4,5,1,2,1,1,1])
from collections import Counter
most_common = Counter(x).most_common(1)[0][0]
print("Most frequent:", most_common)
print("Indices:", np.where(x == most_common))

Most frequent: 1
Indices: (array([0, 5, 7, 8, 9]),)


In [ ]:
# q1 e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = np.sum(gfg)

# ii. Row-wise sum
row_sum = np.sum(gfg, axis=1)

# iii. Column-wise sum
col_sum = np.sum(gfg, axis=0)

print(total_sum)
print(row_sum)
print(col_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
import numpy as np

n_array = np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])

# i. Sum of diagonal elements (Trace)
diag_sum = np.trace(n_array)

# ii. Eigenvalues and iii. Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(n_array)

# iv. Inverse of matrix
inverse_matrix = np.linalg.inv(n_array)

# v. Determinant of matrix
determinant = np.linalg.det(n_array)

# Print results
print("i. Sum of diagonal elements:", diag_sum)
print("ii. Eigenvalues:", eigenvalues)
print("iii. Eigenvectors:\n", eigenvectors)
print("iv. Inverse of matrix:\n", inverse_matrix)
print("v. Determinant of matrix:", determinant)


i. Sum of diagonal elements: 176
ii. Eigenvalues: [98.16835147 28.097044   49.73460452]
iii. Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
iv. Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
v. Determinant of matrix: 137180.0000000001


In [ ]:
import numpy as np

# (i)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

# Matrix multiplication
mul1 = np.matmul(p1, q1)

# Covariance (flattened arrays)
cov1 = np.cov(p1.flatten(), q1.flatten())

print("Matrix Multiplication:\n", mul1)
print("Covariance between p1 and q1:\n", cov1)

# (ii)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
mul2 = np.matmul(p2, q2)

# Covariance (flattened arrays)
cov2 = np.cov(p2.flatten(), q2.flatten())

print(" Matrix Multiplication:\n", mul2)
print("Covariance between p2 and q2:\n", cov2)


Matrix Multiplication:
 [[16 19]
 [26 31]]
Covariance between p1 and q1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
 Matrix Multiplication:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between p2 and q2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner = np.inner(x, y)

# Outer product (flattened)
outer = np.outer(x, y)

# Cartesian product
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print(inner)
print(outer)
print(cartesian)


[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
# Q2
array = np.array([[1, -2, 3],[-4, 5, -6]])

# i. Absolute
abs_array = np.abs(array)

# ii. Percentiles
flat = array.flatten()
percentiles = np.percentile(flat, [25, 50, 75])
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)

print(abs_array)
print(percentiles)
print(col_percentiles)
print(row_percentiles)

# iii. Stats
mean = np.mean(flat)
median = np.median(flat)
std = np.std(flat)

col_mean = np.mean(array, axis=0)
row_mean = np.mean(array, axis=1)

print(mean, median, std)
print(col_mean)
print(row_mean)


[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

print(floor_vals)
print(ceil_vals)
print(trunc_vals)
print(round_vals)


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array
indices_sorted = np.argsort(array)

# iii. 4 smallest elements
smallest_4 = np.sort(array)[:4]

# iv. 5 largest elements
largest_5 = np.sort(array)[-5:]

print("i. Sorted array:", sorted_array)
print("ii. Indices of sorted array:", indices_sorted)
print("iii. 4 smallest elements:", smallest_4)
print("iv. 5 largest elements:", largest_5)


i. Sorted array: [ 10  16  16  52  54  62 453]
ii. Indices of sorted array: [0 3 4 1 5 2 6]
iii. 4 smallest elements: [10 16 16 52]
iv. 5 largest elements: [ 16  52  54  62 453]


In [ ]:
# Q4
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("gray_image.txt", arr, fmt='%d')
        print("Saved grayscale image array.")
    else:
        r, g, b = arr[:,:,0], arr[:,:,1], arr[:,:,2]
        np.savetxt("rgb_r.txt", r, fmt='%d')
        np.savetxt("rgb_g.txt", g, fmt='%d')
        np.savetxt("rgb_b.txt", b, fmt='%d')
        print("Saved RGB image arrays.")


In [ ]:

img_to_array('/content/tree-on-a-hill-grayscale.png')
img_to_array('/content/Desktop-hd-3d-nature-images-download.jpg')

Saved grayscale image array.
Saved RGB image arrays.


In [ ]:
# Load grayscale
gray_image = np.loadtxt("gray_image.txt")

# Load RGB
r = np.loadtxt("rgb_r.txt")
g = np.loadtxt("rgb_g.txt")
b = np.loadtxt("rgb_b.txt")

print(gray_image.shape)
print(r.shape, g.shape, b.shape)

(660, 440)
(1920, 2560) (1920, 2560) (1920, 2560)
